apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-test-app
spec:
  replicas: 2 #number of pods
  selector:
    matchLabels:
      app: kubernetes-test-app
  template:
    metadata:
      labels:
        app: kubernetes-test-app
    spec:
      containers:
      - name: kubernetes-test-app
        image: kubernetes-test-app:latest
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-test-app
spec:
  selector:
    app: kubernetes-test-app
  ports:
  - port: 8080
    targetPort: 5000

